config/routes.rb
Rails.application.routes.draw do
  resources :dishes
  resources :movies
  get 'top/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'top#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
    has_and_belongs_to_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_and_belongs_to_many :dishes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dish_params
      params.require(:dish).permit(:name, :description)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  #def index
  #  @movies = Movie.all
  #end
  def index
    if params[:search]
      filtering = true
      filter_query = params[:search]
    end

    if filtering == true and filter_query[:title]
      sql_like = "%#{filter_query[:title]}%"
      @movies = Movie.where('title like ?', sql_like)
      return
    end
    
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :description)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/dishes/_form.html.erb
<%= form_with(model: dish, local: true) do |form| %>
  <% if dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
        <% dish.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dishes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dishes.each do |dish| %>
      <tr>
        <td><%= dish.name %></td>
        <td><%= dish.description %></td>
        <td><%= link_to 'Show', dish %></td>
        <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
        <td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dish', new_dish_path %>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dish.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @dish.description %>
</p>

<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookpadInternship2020SummerPbl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<div class='container h-100'>
<div class='row h-100' style='padding-top: .5em;'>
<div class='col-sm text-center'>

<%= form_with scope: :search, url: 'movies', method: :get, local: true do |form| %>
  <p>
  <%= form.text_field :title, :placeholder => '映画、ドラマの名前' %>
  <%= form.submit 'さがす' %>
  </p>
<% end %>

</div>
</div>

<div class='row'><div class='col-sm' style='margin-left: 2em;'><h2>検索結果</h2></div></div>

<% @movies.each do |movie| %>
  <div class='row'>
  <div class='col-sm'>
  <div class="card mx-auto" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= movie.title %></h5>
      <p class="card-text"><%= movie.description %></p>
      <a href="<%= movie_path(movie) %>" class="btn btn-primary stretched-link text-white">登場する料理を見る</a>
    </div>
  </div>
  </div>
  </div>
  <% end %>




<!--
<div class='row'>
<% @movies.each do |movie| %>
    <%= link_to movie.title, movie %>
    <%= movie.description %>
<% end %>
</div>
</div>
-->

<!--
<h1>検索結果</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.description %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

-->

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<div class='container h-100'>
<div class='row h-100' style='padding-top: .5em;'>
<div class='col-sm'>

<p>
  <strong>タイトル</strong>: <%= @movie.title %>
</p>

<p>
  <strong>解説:</strong>
  <%= @movie.description %>
</p>


</div>
</div>

<div class='row'><div class='col-sm'><p><strong>作品に登場した料理:</strong></p></div></div>

<% @movie.dishes.each do |dish| %>
  <div class='row'>
  <div class='col-sm'>
  <div class="card mx-auto" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= dish.name %></h5>
      <p class="card-text"><%= dish.description %></p>
      <a href="https://cookpad.com/search/<%= dish.name %>" class="btn btn-primary text-white" style='margin-bottom: 1em;'>クックパッドでレシピを検索</a>
      <a href="https://www.google.com/search?q=<%= dish.name %>" class="btn btn-primary text-white" style='margin-bottom: 1em;'>Googleで料理を検索</a>
    </div>
  </div>
  </div>
  </div>
  <% end %>

</div>

<!--

<p>
  <strong>タイトル</strong>: <%= @movie.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>作品に登場した料理:</strong>
  <% @movie.dishes.each do |d| %>
    <div style='margin: .5em; margin-bottom: 2em;'>
    <div><strong><%= d.name %></strong></div>
    <div><%== d.description %></div>
    <div style='margin: .5em;'><a href='https://cookpad.com/search/<%= d.name %>'>クックパッドでレシピを検索</a></div>
    <div style='margin: .5em;'><a href='https://www.google.com/search?q=<%= d.name %>'>Googleで料理を検索</a></div>
    </div>
  <% end %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

-->

app/views/top/index.html.erb
<div class='container h-100'>
<div class='row h-100' style='padding-top: 5em;'>
<div class='col-sm text-center'>
<h1><strong>Dramatic Dish!</strong></h1>
</div>
<div class='col-sm text-center'>
<h2 style='font-size: 120%;'>
ドラマ・映画の名前で料理を検索！
</h2>
<%= form_with scope: :search, url: 'movies', method: :get, local: true do |form| %>
    <p>
    <%= form.text_field :title, :placeholder => '映画、ドラマの名前' %>
    <%= form.submit 'さがす' %>
    </p>
<% end %>
</div>
<div class='col-sm'></div>
</div>
</div>